Homework 4
elyaishere/afina pull request #6
Opened 2021-03-22 23:01 UTC by elyaishere

2021-03-24 09:22 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +                empty_condition.wait(lock);
Этот condition_variable _не про то_, что потоки завершились, он про то, что задача появилась

2021-03-24 09:22 UTC, xphoenix commented on include/afina/concurrency/Executor.h
> +            threads.emplace_back([this, exec]() {
не надо дублировать такой код

2021-03-24 09:24 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +                                return;
Лучше ```return``` по середине таких циклов не использовать

2021-03-24 09:26 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +                    if (tasks.empty()) {
```
while (!tasks.empty() || state == kRun) {
if (tasks.empty() && state != kStopped) {
     status = wait(_lock);
     if (status == timeout) {
        continue;
     }
}
...
```

2021-04-10 17:40 UTC, Fen99 requested changes

2021-04-10 17:40 UTC, Fen99 commented on src/concurrency/Executor.cpp
> +                        auto wt = pool->empty_condition.wait_for(lock, pool->_idle_time);
Не учтен случай, если wait_for просыпается до таймаута.
```
while (!tasks.empty() || state == kRun) {
   wait_until_time = time::now() + idle_time;
   wait_result = ...;
   while (tasks.empty()) {
       empty_condition.wait_until(lock, wait_until_time);
       if (timeout) { wait_result = timeout; break; }
       else { if (tasks.empty()) { continue; } else { wait_result = new_task; } }  // Внезапное пробуждение
   }
   
   if (wait_result == timeout) { /* continue или завершение, если это лишний поток > low_watermark */}
   if (wait_result == new_task) { /* исполняем */
}

2021-04-10 17:40 UTC, Fen99 commented on src/concurrency/Executor.cpp
> +                std::function<void()> task;
void() noexept

2021-05-01 09:07 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +        if (state == State::kStopped) {
А как это без лока, да в общую память?

2021-05-01 09:16 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +                        }else { // внезапное пробуждение
весь этот else - абсолютно бесполезная хрень

2021-05-01 09:19 UTC, xphoenix commented on src/concurrency/Executor.cpp
> +            if (_working_threads == 0) {
Нафига вот тут вот это, если оно выставляется в routine

2021-05-01 09:44 UTC, merged